### ISSUE TITLE
Crash on OS X

### ISSUE THREAD

**Issue by mehdideveloper** [dmitryelj/SDR-Frequency-Plotter-OSX#1]
Hi
It seems the app is looking for the shared libraries in a hard-coded path. 
I ran it on OS X 10.11.4 and it crashed with "image not found" error:

> Library not loaded: /Users/dmitriieliuseev/Stash/TestApps/SoapySDR-master/build/lib/libSoapySDR.0.5-0.dylib

**Comment by dmitryelj** [comment]
Hi,
Thanks for the feedback. I rebuilded the binary, please download and check again.

Thanks.

**Comment by mehdideveloper** [comment]
It' still the same !

```
Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  **Library not loaded: /Users/dmitriieliuseev/Stash/TestApps/SoapySDR-master/build/lib/libSoapySDR.0.5-0.dylib**
  Referenced from: /Users/USER/Documents/*/FrequencyPlotter.app/Contents/MacOS/FrequencyPlotter
  Reason: image not found
```

**Comment by dmitryelj** [comment]
Hi,

Thanks for the feedback.
Problem is, there are no hardcoded paths in the application. It looks like,
you need to install SoapySDR in OS X before using the app.

Can you please do this, using this instruction?
1) Download SoapySDR-master.zip from https://github.com/pothosware/SoapySDR
(use "download zip")
2) Build using this guide
https://github.com/pothosware/SoapySDR/wiki/BuildGuide (see "Unix
instructions" section)

Later I'll make GUI installer once :)

Thanks,
Dmitrii

2016-04-10 23:23 GMT+02:00 mehdideveloper notifications@github.com:

**Comment by mehdideveloper** [comment]
Hi Dmitri
I've already built and installed SoapySDR.
I have "/usr/local/lib/libSoapySDR.dylib"
Also running "which SoapySDRUtil" gives me the path to my installation of SoapySDR.

I looked at the binary with a disassembler and here's a part of its imports:
http://i67.tinypic.com/rmtl3a.png

**Comment by dmitryelj** [comment]
Hi,

Thanks for help, its great. I've found where the path was added.

I uploaded a new binary, inside there are 2 variants, please check which of
them is working.
https://github.com/dmitryelj/SDR-Frequency-Plotter-OSX/tree/master/Bin

Best regards,
Dmitrii

2016-04-11 10:42 GMT+02:00 mehdideveloper notifications@github.com:

**Comment by mehdideveloper** [comment]
Hi Dmitrii
The provided binaries are tied to a specific version of SoapySDR library (libSoapySDR.0.5-0.dylib)
I had version 0.5-1, so at first the app crashed and I had to rename "libSoapySDR.0.5-1.dylib" to "libSoapySDR.0.5-0.dylib" to fix the error.
You should use the generic name (libSoapySDR.dylib), not the name with version number.
If you take a look at the installation path (usually /usr/local/lib/), you'll see that "libSoapySDR.dylib" is a symbolic link to the original file (0.4-2 or 0.5-0 or 0.5-1 or whatever version installed on the user's system)

Thanks

**Comment by mehdideveloper** [comment]
Now there is another problem.
I can run the application, but as soon as I choose the "SDRPlay" in the list and click on "Start" button, the app crashes!

```
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY
...
Application Specific Information:
Performing @selector(onButtonReceiverStart:) from sender NSButton 0x7fef1ae35ed0

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libc++.1.dylib                
1   Home.SpectrumGraph              0x000000010b96ed1a -[SoapyReceiverImpl initLib:library:] + 1390
2   Home.SpectrumGraph              0x000000010b9753f1 _TFC16FrequencyPlotter18SoapyReceiverModel15connectReceiverfT_Sb + 417
3   Home.SpectrumGraph              0x000000010b98508c 
.....

```

For your info: I can use SDRPlay on my system with CubicSDR (so, my installation of SoapySDR is OK)

**Comment by dmitryelj** [comment]
Hi,

Thanks again for the feedback, it looks that new Soapy lib is not 100%
compatible with the old one. OMG, dll hell in action :)

I rebuilded the app with a new version, now it should work. Please test
binaries in "1" and "2" folders.
URL is the same:
https://github.com/dmitryelj/SDR-Frequency-Plotter-OSX/tree/master/Bin

Thanks,
Dmitrii

2016-04-11 22:44 GMT+02:00 mehdideveloper notifications@github.com:

**Comment by mehdideveloper** [comment]
Ok. Now it works on my machine 
(OS X 10.11.4 , libSoapySDR 0.5-1)

**Comment by dmitryelj** [comment]
Thanks.
Which version is working btw, from folder 1 or 2? I used different library
paths inside.

Dmitrii

2016-04-12 7:53 GMT+02:00 mehdideveloper notifications@github.com:

**Comment by mehdideveloper** [comment]
Both of them work on my system.
I have "libSoapySDR.dylib" installed on  "/usr/local/lib/"
